name: C/C++ CI

on: [push]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [Win32, x64]
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 16 2019" -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release
    - name: Prepare artifacts
      shell: cmd
      run: |
        mkdir dist
        copy build\src\vsfilter\Release\VSFilterMod.dll dist\VSFilterMod.dll
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VSFilterMod_${{ matrix.arch }}
        path: dist
